server {
    listen 80;
    server_name localhost;

    # 1. Раздаем наш фронтенд (HTML + JS)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 2. Проксируем запросы к данным на контейнер PostgREST
    location /api/ {
        proxy_pass http://api_gateway:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}